import { Problem, Strategy } from "../Problem";
import ProblemManager from "../ProblemManager";
const title: string = "Cyclical figurate numbers";
const description: string = "\nTriangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:\nTriangle\n\u00A0\nP3,n=n(n+1)/2\n\u00A0\n1, 3, 6, 10, 15, ...\nSquare\n\u00A0\nP4,n=n2\n\u00A0\n1, 4, 9, 16, 25, ...\nPentagonal\n\u00A0\nP5,n=n(3n\u22121)/2\n\u00A0\n1, 5, 12, 22, 35, ...\nHexagonal\n\u00A0\nP6,n=n(2n\u22121)\n\u00A0\n1, 6, 15, 28, 45, ...\nHeptagonal\n\u00A0\nP7,n=n(5n\u22123)/2\n\u00A0\n1, 7, 18, 34, 55, ...\nOctagonal\n\u00A0\nP8,n=n(3n\u22122)\n\u00A0\n1, 8, 21, 40, 65, ...\nThe ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.\nThe set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).\nEach polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.\nThis is the only set of 4-digit numbers with this property.\nFind the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.\n\n";
const index: number = 61;
class Solution extends Strategy {
    public validateArgs(args: any[]) {
        throw new Error("Method not implemented.");
    }
    public solve(args: any[]) {
        throw new Error("Method not implemented.");
    }
}
const solution = new Solution();
const ProblemImplementation = new Problem(title, description, solution);
ProblemManager.register(index, ProblemImplementation);
