import { Problem, Strategy } from "../Problem";
const title: string = "An enormous factorial";
const description: string = "\n\nFor any prime p the number N(p,q) is defined by\nN(p,q) = \u2211n=0 to q Tn*pn with Tn generated by the following random number generator:\n\nS0 = 290797\nSn+1 = Sn2 mod 50515093\nTn = Sn mod p\n\n\nLet Nfac(p,q) be the factorial of N(p,q).\nLet NF(p,q) be the number of factors p in Nfac(p,q).\n\n\nYou are given that NF(3,10000) mod 320=624955285.\n\n\nFind NF(61,107) mod 6110\n\n    \n\n\n";
const index: number = 288;
class Solution extends Strategy {
    public validateArgs(args: any[]) {
        throw new Error("Method not implemented.");
    }
    public solve(args: any[]) {
        throw new Error("Method not implemented.");
    }
}
const solution = new Solution();
export const ProblemImplementation = new Problem(index, title, description, solution);
