import { Problem, Strategy } from "../Problem";
const title: string = "Distinct powers";
const description: string = "\n\nConsider all integer combinations of ab for 2 \u2264 a \u2264 5 and 2 \u2264 b \u2264 5:\n22=4, 23=8, 24=16, 25=32\n32=9, 33=27, 34=81, 35=243\n42=16, 43=64, 44=256, 45=1024\n52=25, 53=125, 54=625, 55=3125\nIf they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:\n4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125\nHow many distinct terms are in the sequence generated by ab for 2 \u2264 a \u2264 100 and 2 \u2264 b \u2264 100?\n\n";
const index: number = 29;
class Solution extends Strategy {
    public validateArgs(args: any[]) {
        throw new Error("Method not implemented.");
    }
    public solve(args: any[]) {
        throw new Error("Method not implemented.");
    }
}
const solution = new Solution();
export const ProblemImplementation = new Problem(index, title, description, solution);
